### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by MP3Martin** [rjhn/DiscordBotClient#1]
![Screenshot from 2022-02-06 19-57-48](https://user-images.githubusercontent.com/60501493/152696938-4c7c5410-62a4-4860-863f-071e04d0da9b.png)

**Comment by BigDavLuk** [comment]
bro hacked me ...

**Comment by MP3Martin** [comment]
Use this if you actually need a bot client: https://github.com/aiko-chan-ai/DiscordBotClient
